"""API routers grouped by domain."""
# flake8: noqa: F401, F822

from backend.api import (academy, academy_core, admin, agenda, agenda_core, agents,
                         analytics,
                         assets, auth, auth_v2, chat, cms, cms_v2, community, content, crm,
                         crm_core, dashboard, donations, evangelism, evangelism_multiplication,
                         evangelism_notifications, evangelism_rankings, evangelism_reports,
                         finance, governance,
                         graph, kernel, messaging, prayer, proyectos,
                         public, spiritual_life, support, system, workspace)

__all__ = [
    "academy",
    "admin",
    "agenda",
    "agents",
    "analytics",
    "assets",
    "auth",
    "auth_v2",
    "chat",
    "cms",
    "cms_v2",
    "community",
    "content",
    "crm",
    "dashboard",
    "donations",
    "evangelism",
    "evangelism_multiplication",
    "evangelism_notifications",
    "evangelism_rankings",
    "evangelism_reports",
    "finance",
    "governance",
    "graph",
    "kernel",
    "messaging",
    "prayer",
    "projects",
    "proyectos",
    "public",
    "spiritual_life",
    "support",
    "system",
    "workspace",
]
