import type { Config } from "tailwindcss";

const config: Config = {
    darkMode: "class",
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "primary": "#1973f0",
                "navy-dark": "#0A192F",
                "sky-blue": "#00B4DB",
                "background-light": "#f6f7f8",
                "background-dark": "#050A10",
                "ccf-blue-dark": "rgb(0, 27, 72)",
                "ccf-blue-medium": "rgb(0, 69, 129)",
                "ccf-blue-light": "rgb(1, 138, 189)",
                "ccf-blue-pale": "rgb(221, 232, 240)",
                glass: "rgba(255, 255, 255, 0.1)",
                "glass-border": "rgba(255, 255, 255, 0.2)",
                                "site-on-tertiary-fixed-variant": "var(--site-on-tertiary-fixed-variant)",
                "site-surface-container-lowest": "var(--site-surface-container-lowest)",
                "site-surface-tint": "var(--site-surface-tint)",
                "site-on-background": "var(--site-on-background)",
                "site-inverse-primary": "var(--site-inverse-primary)",
                "site-on-surface": "var(--site-on-surface)",
                "site-secondary-fixed-dim": "var(--site-secondary-fixed-dim)",
                "site-outline": "var(--site-outline)",
                "site-on-error-container": "var(--site-on-error-container)",
                "site-tertiary-fixed-dim": "var(--site-tertiary-fixed-dim)",
                "site-on-surface-variant": "var(--site-on-surface-variant)",
                "site-secondary-container": "var(--site-secondary-container)",
                "site-outline-variant": "var(--site-outline-variant)",
                "site-primary-fixed-dim": "var(--site-primary-fixed-dim)",
                "site-inverse-surface": "var(--site-inverse-surface)",
                "site-tertiary": "var(--site-tertiary)",
                "site-surface-container-high": "var(--site-surface-container-high)",
                "site-error-container": "var(--site-error-container)",
                "site-surface-dim": "var(--site-surface-dim)",
                "site-on-primary-container": "var(--site-on-primary-container)",
                "site-on-error": "var(--site-on-error)",
                "site-background": "var(--site-background)",
                "site-on-secondary": "var(--site-on-secondary)",
                "site-tertiary-fixed": "var(--site-tertiary-fixed)",
                "site-on-primary": "var(--site-on-primary)",
                "site-surface-container-highest": "var(--site-surface-container-highest)",
                "site-inverse-on-surface": "var(--site-inverse-on-surface)",
                "site-surface-variant": "var(--site-surface-variant)",
                "site-surface": "var(--site-surface)",
                "site-primary-container": "var(--site-primary-container)",
                "site-on-primary-fixed-variant": "var(--site-on-primary-fixed-variant)",
                "site-on-secondary-container": "var(--site-on-secondary-container)",
                "site-on-tertiary-fixed": "var(--site-on-tertiary-fixed)",
                "site-on-primary-fixed": "var(--site-on-primary-fixed)",
                "site-secondary-fixed": "var(--site-secondary-fixed)",
                "site-on-tertiary": "var(--site-on-tertiary)",
                "site-primary": "var(--site-primary)",
                "site-on-tertiary-container": "var(--site-on-tertiary-container)",
                "site-primary-fixed": "var(--site-primary-fixed)",
                "site-surface-container-low": "var(--site-surface-container-low)",
                "site-surface-bright": "var(--site-surface-bright)",
                "site-error": "var(--site-error)",
                "site-surface-container": "var(--site-surface-container)",
                "site-tertiary-container": "var(--site-tertiary-container)",
                "site-secondary": "var(--site-secondary)",
                "site-on-secondary-fixed-variant": "var(--site-on-secondary-fixed-variant)",
                "site-on-secondary-fixed": "var(--site-on-secondary-fixed)"
            },
            fontFamily: {
                "display": ["Manrope", "sans-serif"],
                "sans": ["Manrope", "sans-serif"],
                "headline": ["var(--font-manrope)", "Manrope", "sans-serif"],
                "body": ["var(--font-inter)", "Inter", "sans-serif"],
                "label": ["var(--font-inter)", "Inter", "sans-serif"]
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "1rem",
                "2xl": "1.5rem",
                "3xl": "2rem",
                "4xl": "2.5rem",
                "full": "9999px"
            },
            backdropBlur: {
                xs: "2px",
            },
            keyframes: {
                gradient: {
                    "0%": { backgroundPosition: "0% 50%" },
                    "50%": { backgroundPosition: "100% 50%" },
                    "100%": { backgroundPosition: "0% 50%" },
                },
            },
            animation: {
                "gradient-xy": "gradient 3s ease infinite",
            },
        },
    },
    plugins: [],
};
export default config;
