import type { Config } from "tailwindcss";

const config: Config = {
    darkMode: "class",
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "primary": "#1973f0",
                "navy-dark": "#0A192F",
                "sky-blue": "#00B4DB",
                "background-light": "#f6f7f8",
                "background-dark": "#050A10",
                glass: "rgba(255, 255, 255, 0.1)",
                "glass-border": "rgba(255, 255, 255, 0.2)",
                                "faro-on-tertiary-fixed-variant": "var(--faro-on-tertiary-fixed-variant)",
                "faro-surface-container-lowest": "var(--faro-surface-container-lowest)",
                "faro-surface-tint": "var(--faro-surface-tint)",
                "faro-on-background": "var(--faro-on-background)",
                "faro-inverse-primary": "var(--faro-inverse-primary)",
                "faro-on-surface": "var(--faro-on-surface)",
                "faro-secondary-fixed-dim": "var(--faro-secondary-fixed-dim)",
                "faro-outline": "var(--faro-outline)",
                "faro-on-error-container": "var(--faro-on-error-container)",
                "faro-tertiary-fixed-dim": "var(--faro-tertiary-fixed-dim)",
                "faro-on-surface-variant": "var(--faro-on-surface-variant)",
                "faro-secondary-container": "var(--faro-secondary-container)",
                "faro-outline-variant": "var(--faro-outline-variant)",
                "faro-primary-fixed-dim": "var(--faro-primary-fixed-dim)",
                "faro-inverse-surface": "var(--faro-inverse-surface)",
                "faro-tertiary": "var(--faro-tertiary)",
                "faro-surface-container-high": "var(--faro-surface-container-high)",
                "faro-error-container": "var(--faro-error-container)",
                "faro-surface-dim": "var(--faro-surface-dim)",
                "faro-on-primary-container": "var(--faro-on-primary-container)",
                "faro-on-error": "var(--faro-on-error)",
                "faro-background": "var(--faro-background)",
                "faro-on-secondary": "var(--faro-on-secondary)",
                "faro-tertiary-fixed": "var(--faro-tertiary-fixed)",
                "faro-on-primary": "var(--faro-on-primary)",
                "faro-surface-container-highest": "var(--faro-surface-container-highest)",
                "faro-inverse-on-surface": "var(--faro-inverse-on-surface)",
                "faro-surface-variant": "var(--faro-surface-variant)",
                "faro-surface": "var(--faro-surface)",
                "faro-primary-container": "var(--faro-primary-container)",
                "faro-on-primary-fixed-variant": "var(--faro-on-primary-fixed-variant)",
                "faro-on-secondary-container": "var(--faro-on-secondary-container)",
                "faro-on-tertiary-fixed": "var(--faro-on-tertiary-fixed)",
                "faro-on-primary-fixed": "var(--faro-on-primary-fixed)",
                "faro-secondary-fixed": "var(--faro-secondary-fixed)",
                "faro-on-tertiary": "var(--faro-on-tertiary)",
                "faro-primary": "var(--faro-primary)",
                "faro-on-tertiary-container": "var(--faro-on-tertiary-container)",
                "faro-primary-fixed": "var(--faro-primary-fixed)",
                "faro-surface-container-low": "var(--faro-surface-container-low)",
                "faro-surface-bright": "var(--faro-surface-bright)",
                "faro-error": "var(--faro-error)",
                "faro-surface-container": "var(--faro-surface-container)",
                "faro-tertiary-container": "var(--faro-tertiary-container)",
                "faro-secondary": "var(--faro-secondary)",
                "faro-on-secondary-fixed-variant": "var(--faro-on-secondary-fixed-variant)",
                "faro-on-secondary-fixed": "var(--faro-on-secondary-fixed)"
            },
            fontFamily: {
                "display": ["Manrope", "sans-serif"],
                "sans": ["Manrope", "sans-serif"],
                "headline": ["var(--font-manrope)", "Manrope", "sans-serif"],
                "body": ["var(--font-inter)", "Inter", "sans-serif"],
                "label": ["var(--font-inter)", "Inter", "sans-serif"]
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "1rem",
                "2xl": "1.5rem",
                "3xl": "2rem",
                "4xl": "2.5rem",
                "full": "9999px"
            },
            backdropBlur: {
                xs: "2px",
            },
        },
    },
    plugins: [],
};
export default config;
