import type { Config } from "tailwindcss";

const config: Config = {
    darkMode: "class",
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "primary": "hsl(var(--primary) / <alpha-value>)",
                "success": "hsl(var(--success) / <alpha-value>)",
                "warning": "hsl(var(--warning) / <alpha-value>)",
                "info": "hsl(var(--info) / <alpha-value>)",
                "danger": "hsl(var(--danger) / <alpha-value>)",
                "success-text": "hsl(var(--success-text) / <alpha-value>)",
                "warning-text": "hsl(var(--warning-text) / <alpha-value>)",
                "info-text": "hsl(var(--info-text) / <alpha-value>)",
                "danger-text": "hsl(var(--danger-text) / <alpha-value>)",
                "success-muted": "hsl(var(--success-muted) / <alpha-value>)",
                "warning-muted": "hsl(var(--warning-muted) / <alpha-value>)",
                "info-muted": "hsl(var(--info-muted) / <alpha-value>)",
                "danger-muted": "hsl(var(--danger-muted) / <alpha-value>)",
                "navy-dark": "hsl(var(--navy-dark) / <alpha-value>)",
                "sky-blue": "hsl(var(--sky-blue) / <alpha-value>)",
                "background-light": "hsl(var(--background-light) / <alpha-value>)",
                "background-dark": "hsl(var(--background-dark) / <alpha-value>)",
                "ccf-blue-dark": "hsl(var(--ccf-blue-dark) / <alpha-value>)",
                "ccf-blue-medium": "hsl(var(--ccf-blue-medium) / <alpha-value>)",
                "ccf-blue-light": "hsl(var(--ccf-blue-light) / <alpha-value>)",
                "ccf-blue-pale": "hsl(var(--ccf-blue-pale) / <alpha-value>)",
                glass: "hsl(var(--glass))",
                "glass-border": "hsl(var(--glass-border))",
                "admin-bg-deep": "var(--admin-bg-deep)",
                "admin-bg-surface": "var(--admin-bg-surface)",
                "admin-bg-elevated": "var(--admin-bg-elevated)",
                "admin-bg-primary": "var(--admin-bg-primary)",
                "admin-bg-secondary": "var(--admin-bg-secondary)",
                "admin-bg-tertiary": "var(--admin-bg-tertiary)",
                "admin-bg-input": "var(--admin-bg-input)",
                "admin-border": "var(--admin-border)",
                "surface-1": "hsl(var(--surface-1) / <alpha-value>)",
                "surface-2": "hsl(var(--surface-2) / <alpha-value>)",
                "surface-3": "hsl(var(--surface-3) / <alpha-value>)",
                                "site-on-tertiary-fixed-variant": "var(--site-on-tertiary-fixed-variant)",
                "site-surface-container-lowest": "var(--site-surface-container-lowest)",
                "site-surface-tint": "var(--site-surface-tint)",
                "site-on-background": "var(--site-on-background)",
                "site-inverse-primary": "var(--site-inverse-primary)",
                "site-on-surface": "var(--site-on-surface)",
                "site-secondary-fixed-dim": "var(--site-secondary-fixed-dim)",
                "site-outline": "var(--site-outline)",
                "site-on-error-container": "var(--site-on-error-container)",
                "site-tertiary-fixed-dim": "var(--site-tertiary-fixed-dim)",
                "site-on-surface-variant": "var(--site-on-surface-variant)",
                "site-secondary-container": "var(--site-secondary-container)",
                "site-outline-variant": "var(--site-outline-variant)",
                "site-primary-fixed-dim": "var(--site-primary-fixed-dim)",
                "site-inverse-surface": "var(--site-inverse-surface)",
                "site-tertiary": "var(--site-tertiary)",
                "site-surface-container-high": "var(--site-surface-container-high)",
                "site-error-container": "var(--site-error-container)",
                "site-surface-dim": "var(--site-surface-dim)",
                "site-on-primary-container": "var(--site-on-primary-container)",
                "site-on-error": "var(--site-on-error)",
                "site-background": "var(--site-background)",
                "site-on-secondary": "var(--site-on-secondary)",
                "site-tertiary-fixed": "var(--site-tertiary-fixed)",
                "site-on-primary": "var(--site-on-primary)",
                "site-surface-container-highest": "var(--site-surface-container-highest)",
                "site-inverse-on-surface": "var(--site-inverse-on-surface)",
                "site-surface-variant": "var(--site-surface-variant)",
                "site-surface": "var(--site-surface)",
                "site-primary-container": "var(--site-primary-container)",
                "site-on-primary-fixed-variant": "var(--site-on-primary-fixed-variant)",
                "site-on-secondary-container": "var(--site-on-secondary-container)",
                "site-on-tertiary-fixed": "var(--site-on-tertiary-fixed)",
                "site-on-primary-fixed": "var(--site-on-primary-fixed)",
                "site-secondary-fixed": "var(--site-secondary-fixed)",
                "site-on-tertiary": "var(--site-on-tertiary)",
                "site-primary": "var(--site-primary)",
                "site-on-tertiary-container": "var(--site-on-tertiary-container)",
                "site-primary-fixed": "var(--site-primary-fixed)",
                "site-surface-container-low": "var(--site-surface-container-low)",
                "site-surface-bright": "var(--site-surface-bright)",
                "site-error": "var(--site-error)",
                "site-surface-container": "var(--site-surface-container)",
                "site-tertiary-container": "var(--site-tertiary-container)",
                "site-secondary": "var(--site-secondary)",
                "site-on-secondary-fixed-variant": "var(--site-on-secondary-fixed-variant)",
                "site-on-secondary-fixed": "var(--site-on-secondary-fixed)"
            },
            fontFamily: {
                // ── Connected to next/font/google CSS variables (see layout.tsx) ──
                // var(--font-*) is injected into <html> by Next.js at build time.
                // Static fallback strings ensure prerender/SSR correctness.
                "display":  ["var(--font-roboto)", "Roboto", "var(--font-open-sans)", "Open Sans", "var(--font-inter)", "Inter", "-apple-system", "sans-serif"],
                "sans":     ["var(--font-roboto)", "Roboto", "var(--font-open-sans)", "Open Sans", "var(--font-inter)", "Inter", "-apple-system", "sans-serif"],
                "headline": ["var(--font-roboto)", "Roboto", "var(--font-open-sans)", "Open Sans", "-apple-system", "sans-serif"],
                "body":     ["var(--font-inter)", "Inter", "-apple-system", "sans-serif"],
                "label":    ["var(--font-inter)", "Inter", "-apple-system", "sans-serif"],
                "mono":     ["JetBrains Mono", "Fira Code", "ui-monospace", "monospace"],
            },
            fontSize: {
                // ── Semantic type scale (maps to --text-* CSS tokens) ──
                // Use class names: text-2xs, text-xs, text-sm, text-base, etc.
                "2xs":  ["var(--text-2xs)",  { lineHeight: "var(--leading-tight)" }],
                "xs":   ["var(--text-xs)",   { lineHeight: "var(--leading-normal)" }],
                "sm":   ["var(--text-sm)",   { lineHeight: "var(--leading-normal)" }],
                "base": ["var(--text-base)", { lineHeight: "var(--leading-normal)" }],
                "md":   ["var(--text-md)",   { lineHeight: "var(--leading-normal)" }],
                "lg":   ["var(--text-lg)",   { lineHeight: "var(--leading-snug)" }],
                "xl":   ["var(--text-xl)",   { lineHeight: "var(--leading-tight)" }],
                "2xl":  ["var(--text-2xl)",  { lineHeight: "var(--leading-tight)" }],
                "3xl":  ["var(--text-3xl)",  { lineHeight: "var(--leading-tight)" }],
                "4xl":  ["var(--text-4xl)",  { lineHeight: "1.1" }],
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "1rem",
                "2xl": "1.5rem",
                "3xl": "2rem",
                "4xl": "2.5rem",
                "full": "9999px"
            },
            backdropBlur: {
                xs: "2px",
            },
            keyframes: {
                gradient: {
                    "0%": { backgroundPosition: "0% 50%" },
                    "50%": { backgroundPosition: "100% 50%" },
                    "100%": { backgroundPosition: "0% 50%" },
                },
            },
            animation: {
                "gradient-xy": "gradient 3s ease infinite",
            },
        },
    },
    plugins: [],
};
export default config;
