"""add FK indexes to 111 foreign key columns (performance)

Auditoría de calidad backend (ses_01d60c45): ~87 FKs sin índice causan
full table scans en joins y ON DELETE/UPDATE cascades. Esta migración
añade B-Tree indexes a todas las columnas FK que no tenían índice propio
y no son parte de la PK (que ya está indexada por el clúster).

Pure DDL aditivo — no cambia datos ni contratos. Reversible: el downgrade
elimina todos los índices creados.

Revision ID: 20260809_0002_fk_indexes
Revises: 20260809_0001_sede_vol_sup_task
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "20260809_0002_fk_indexes"
down_revision: Union[str, None] = "20260809_0001_sede_vol_sup_task"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 111 FK indexes — generated from live DB inspection
    # (sa.inspect detected FKs without index and not part of PK).

    op.create_index("ix_academy_activity_logs_course_id", "academy_activity_logs", ["course_id"], unique=False)
    op.create_index("ix_academy_activity_logs_persona_id", "academy_activity_logs", ["persona_id"], unique=False)
    op.create_index("ix_academy_assessment_answers_question_id", "academy_assessment_answers", ["question_id"], unique=False)
    op.create_index("ix_academy_assessment_answers_selected_option_id", "academy_assessment_answers", ["selected_option_id"], unique=False)
    op.create_index("ix_academy_assessment_attempts_assessment_id", "academy_assessment_attempts", ["assessment_id"], unique=False)
    op.create_index("ix_academy_assessment_attempts_enrollment_id", "academy_assessment_attempts", ["enrollment_id"], unique=False)
    op.create_index("ix_academy_assessment_options_question_id", "academy_assessment_options", ["question_id"], unique=False)
    op.create_index("ix_academy_assessment_questions_assessment_id", "academy_assessment_questions", ["assessment_id"], unique=False)
    op.create_index("ix_academy_assessments_course_id", "academy_assessments", ["course_id"], unique=False)
    op.create_index("ix_academy_assessments_lesson_id", "academy_assessments", ["lesson_id"], unique=False)
    op.create_index("ix_academy_assignment_submissions_enrollment_id", "academy_assignment_submissions", ["enrollment_id"], unique=False)
    op.create_index("ix_academy_assignment_submissions_lesson_id", "academy_assignment_submissions", ["lesson_id"], unique=False)
    op.create_index("ix_academy_certificates_enrollment_id", "academy_certificates", ["enrollment_id"], unique=False)
    op.create_index("ix_academy_course_attendance_enrollment_id", "academy_course_attendance", ["enrollment_id"], unique=False)
    op.create_index("ix_academy_course_attendance_recorded_by_persona_id", "academy_course_attendance", ["recorded_by_persona_id"], unique=False)
    op.create_index("ix_academy_courses_sede_id", "academy_courses", ["sede_id"], unique=False)
    op.create_index("ix_academy_formal_acta_entries_acta_id", "academy_formal_acta_entries", ["acta_id"], unique=False)
    op.create_index("ix_academy_formal_acta_entries_enrollment_id", "academy_formal_acta_entries", ["enrollment_id"], unique=False)
    op.create_index("ix_academy_formal_actas_closed_by_persona_id", "academy_formal_actas", ["closed_by_persona_id"], unique=False)
    op.create_index("ix_academy_formal_actas_course_id", "academy_formal_actas", ["course_id"], unique=False)
    op.create_index("ix_academy_forum_comments_author_persona_id", "academy_forum_comments", ["author_persona_id"], unique=False)
    op.create_index("ix_academy_forum_comments_parent_id", "academy_forum_comments", ["parent_id"], unique=False)
    op.create_index("ix_academy_forum_comments_thread_id", "academy_forum_comments", ["thread_id"], unique=False)
    op.create_index("ix_academy_forum_threads_author_persona_id", "academy_forum_threads", ["author_persona_id"], unique=False)
    op.create_index("ix_academy_forum_threads_course_id", "academy_forum_threads", ["course_id"], unique=False)
    op.create_index("ix_academy_lessons_course_id", "academy_lessons", ["course_id"], unique=False)
    op.create_index("ix_accounting_entries_created_by_id", "accounting_entries", ["created_by_id"], unique=False)
    op.create_index("ix_admin_audit_logs_actor_persona_id", "admin_audit_logs", ["actor_persona_id"], unique=False)
    op.create_index("ix_agenda_eventos_organizador_persona_id", "agenda_eventos", ["organizador_persona_id"], unique=False)
    op.create_index("ix_agenda_eventos_sede_id", "agenda_eventos", ["sede_id"], unique=False)
    op.create_index("ix_agenda_participantes_evento_id", "agenda_participantes", ["evento_id"], unique=False)
    op.create_index("ix_agenda_participantes_persona_id", "agenda_participantes", ["persona_id"], unique=False)
    op.create_index("ix_agenda_recursos_sede_id", "agenda_recursos", ["sede_id"], unique=False)
    op.create_index("ix_agenda_reserva_recursos_evento_id", "agenda_reserva_recursos", ["evento_id"], unique=False)
    op.create_index("ix_agenda_reserva_recursos_recurso_id", "agenda_reserva_recursos", ["recurso_id"], unique=False)
    op.create_index("ix_agent_contact_created_by", "agent_contact", ["created_by"], unique=False)
    op.create_index("ix_agent_insights_acknowledged_by_persona_id", "agent_insights", ["acknowledged_by_persona_id"], unique=False)
    op.create_index("ix_agent_journey_triggered_by_persona_id", "agent_journey", ["triggered_by_persona_id"], unique=False)
    op.create_index("ix_agent_knowledge_base_indexed_by", "agent_knowledge_base", ["indexed_by"], unique=False)
    op.create_index("ix_agent_roles_created_by_persona_id", "agent_roles", ["created_by_persona_id"], unique=False)
    op.create_index("ix_agents_created_by_persona_id", "agents", ["created_by_persona_id"], unique=False)
    op.create_index("ix_agents_updated_by_persona_id", "agents", ["updated_by_persona_id"], unique=False)
    op.create_index("ix_auth_password_history_user_id", "auth_password_history", ["user_id"], unique=False)
    op.create_index("ix_auth_refresh_tokens_user_id", "auth_refresh_tokens", ["user_id"], unique=False)
    op.create_index("ix_auth_reset_tokens_user_id", "auth_reset_tokens", ["user_id"], unique=False)
    op.create_index("ix_auth_security_logs_user_id", "auth_security_logs", ["user_id"], unique=False)
    op.create_index("ix_auth_user_badges_badge_id", "auth_user_badges", ["badge_id"], unique=False)
    op.create_index("ix_auth_user_badges_user_id", "auth_user_badges", ["user_id"], unique=False)
    op.create_index("ix_auth_user_module_roles_rol_id", "auth_user_module_roles", ["rol_id"], unique=False)
    op.create_index("ix_auth_user_module_roles_user_id", "auth_user_module_roles", ["user_id"], unique=False)
    op.create_index("ix_auth_users_current_level_id", "auth_users", ["current_level_id"], unique=False)
    op.create_index("ix_auth_users_rol_plataforma_id", "auth_users", ["rol_plataforma_id"], unique=False)
    op.create_index("ix_auth_verification_tokens_user_id", "auth_verification_tokens", ["user_id"], unique=False)
    op.create_index("ix_bank_reconciliations_created_by_id", "bank_reconciliations", ["created_by_id"], unique=False)
    op.create_index("ix_bank_transactions_reconciled_by_id", "bank_transactions", ["reconciled_by_id"], unique=False)
    op.create_index("ix_cms_ab_tests_winner_section_id", "cms_ab_tests", ["winner_section_id"], unique=False)
    op.create_index("ix_cms_content_permissions_created_by_persona_id", "cms_content_permissions", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_custom_entries_author_persona_id", "cms_custom_entries", ["author_persona_id"], unique=False)
    op.create_index("ix_cms_custom_entries_owner_persona_id", "cms_custom_entries", ["owner_persona_id"], unique=False)
    op.create_index("ix_cms_custom_entry_versions_created_by_persona_id", "cms_custom_entry_versions", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_glossary_terms_created_by_persona_id", "cms_glossary_terms", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_media_file_versions_created_by_persona_id", "cms_media_file_versions", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_media_folders_created_by_persona_id", "cms_media_folders", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_media_items_created_by_persona_id", "cms_media_items", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_notifications_actor_persona_id", "cms_notifications", ["actor_persona_id"], unique=False)
    op.create_index("ix_cms_page_versions_created_by_persona_id", "cms_page_versions", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_pages_created_by_persona_id", "cms_pages", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_pages_published_version_id", "cms_pages", ["published_version_id"], unique=False)
    op.create_index("ix_cms_pages_updated_by_persona_id", "cms_pages", ["updated_by_persona_id"], unique=False)
    op.create_index("ix_cms_posts_author_persona_id", "cms_posts", ["author_persona_id"], unique=False)
    op.create_index("ix_cms_posts_created_by_persona_id", "cms_posts", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_posts_updated_by_persona_id", "cms_posts", ["updated_by_persona_id"], unique=False)
    op.create_index("ix_cms_publish_logs_actor_persona_id", "cms_publish_logs", ["actor_persona_id"], unique=False)
    op.create_index("ix_cms_redirects_created_by_persona_id", "cms_redirects", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_search_index_author_persona_id", "cms_search_index", ["author_persona_id"], unique=False)
    op.create_index("ix_cms_search_promotions_created_by_persona_id", "cms_search_promotions", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_sections_created_by_persona_id", "cms_sections", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_sections_updated_by_persona_id", "cms_sections", ["updated_by_persona_id"], unique=False)
    op.create_index("ix_cms_themes_created_by_persona_id", "cms_themes", ["created_by_persona_id"], unique=False)
    op.create_index("ix_cms_themes_updated_by_persona_id", "cms_themes", ["updated_by_persona_id"], unique=False)
    op.create_index("ix_cms_webhooks_created_by_persona_id", "cms_webhooks", ["created_by_persona_id"], unique=False)
    op.create_index("ix_conversations_last_sender_id", "conversations", ["last_sender_id"], unique=False)
    op.create_index("ix_crm_casos_origen_estrategia_id", "crm_casos", ["origen_estrategia_id"], unique=False)
    op.create_index("ix_crm_casos_origen_grupo_id", "crm_casos", ["origen_grupo_id"], unique=False)
    op.create_index("ix_crm_casos_origen_sesion_id", "crm_casos", ["origen_sesion_id"], unique=False)
    op.create_index("ix_crm_events_form_id", "crm_events", ["form_id"], unique=False)
    op.create_index("ix_crm_events_target_role_id", "crm_events", ["target_role_id"], unique=False)
    op.create_index("ix_crm_interacciones_plantilla_usada_id", "crm_interacciones", ["plantilla_usada_id"], unique=False)
    op.create_index("ix_crm_pending_actions_automation_id", "crm_pending_actions", ["automation_id"], unique=False)
    op.create_index("ix_documents_uploaded_by_id", "documents", ["uploaded_by_id"], unique=False)
    op.create_index("ix_estrategias_evangelismo_default_role_id", "estrategias_evangelismo", ["default_role_id"], unique=False)
    op.create_index("ix_event_campaigns_created_by_id", "event_campaigns", ["created_by_id"], unique=False)
    op.create_index("ix_event_campaigns_plantilla_id", "event_campaigns", ["plantilla_id"], unique=False)
    op.create_index("ix_event_identity_challenges_persona_id", "event_identity_challenges", ["persona_id"], unique=False)
    op.create_index("ix_event_registrations_checked_in_by", "event_registrations", ["checked_in_by"], unique=False)
    op.create_index("ix_expense_receipts_uploaded_by_id", "expense_receipts", ["uploaded_by_id"], unique=False)
    op.create_index("ix_expense_reports_approved_by_id", "expense_reports", ["approved_by_id"], unique=False)
    op.create_index("ix_financial_statements_generated_by_id", "financial_statements", ["generated_by_id"], unique=False)
    op.create_index("ix_invoice_payments_created_by_id", "invoice_payments", ["created_by_id"], unique=False)
    op.create_index("ix_invoices_created_by_id", "invoices", ["created_by_id"], unique=False)
    op.create_index("ix_ministries_leader_persona_id", "ministries", ["leader_persona_id"], unique=False)
    op.create_index("ix_persona_ministries_recognized_by_persona_id", "persona_ministries", ["recognized_by_persona_id"], unique=False)
    op.create_index("ix_personas_origen_estrategia_id", "personas", ["origen_estrategia_id"], unique=False)
    op.create_index("ix_project_activity_logs_persona_id", "project_activity_logs", ["persona_id"], unique=False)
    op.create_index("ix_project_attachments_uploader_id", "project_attachments", ["uploader_id"], unique=False)
    op.create_index("ix_project_comments_task_id", "project_comments", ["task_id"], unique=False)
    op.create_index("ix_project_documents_author_id", "project_documents", ["author_id"], unique=False)
    op.create_index("ix_sales_orders_created_by_id", "sales_orders", ["created_by_id"], unique=False)
    op.create_index("ix_sign_requests_created_by_id", "sign_requests", ["created_by_id"], unique=False)
    op.create_index("ix_wiki_page_versions_created_by_persona_id", "wiki_page_versions", ["created_by_persona_id"], unique=False)
    op.create_index("ix_wiki_pages_author_id", "wiki_pages", ["author_id"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_academy_activity_logs_course_id", table_name="academy_activity_logs")
    op.drop_index("ix_academy_activity_logs_persona_id", table_name="academy_activity_logs")
    op.drop_index("ix_academy_assessment_answers_question_id", table_name="academy_assessment_answers")
    op.drop_index("ix_academy_assessment_answers_selected_option_id", table_name="academy_assessment_answers")
    op.drop_index("ix_academy_assessment_attempts_assessment_id", table_name="academy_assessment_attempts")
    op.drop_index("ix_academy_assessment_attempts_enrollment_id", table_name="academy_assessment_attempts")
    op.drop_index("ix_academy_assessment_options_question_id", table_name="academy_assessment_options")
    op.drop_index("ix_academy_assessment_questions_assessment_id", table_name="academy_assessment_questions")
    op.drop_index("ix_academy_assessments_course_id", table_name="academy_assessments")
    op.drop_index("ix_academy_assessments_lesson_id", table_name="academy_assessments")
    op.drop_index("ix_academy_assignment_submissions_enrollment_id", table_name="academy_assignment_submissions")
    op.drop_index("ix_academy_assignment_submissions_lesson_id", table_name="academy_assignment_submissions")
    op.drop_index("ix_academy_certificates_enrollment_id", table_name="academy_certificates")
    op.drop_index("ix_academy_course_attendance_enrollment_id", table_name="academy_course_attendance")
    op.drop_index("ix_academy_course_attendance_recorded_by_persona_id", table_name="academy_course_attendance")
    op.drop_index("ix_academy_courses_sede_id", table_name="academy_courses")
    op.drop_index("ix_academy_formal_acta_entries_acta_id", table_name="academy_formal_acta_entries")
    op.drop_index("ix_academy_formal_acta_entries_enrollment_id", table_name="academy_formal_acta_entries")
    op.drop_index("ix_academy_formal_actas_closed_by_persona_id", table_name="academy_formal_actas")
    op.drop_index("ix_academy_formal_actas_course_id", table_name="academy_formal_actas")
    op.drop_index("ix_academy_forum_comments_author_persona_id", table_name="academy_forum_comments")
    op.drop_index("ix_academy_forum_comments_parent_id", table_name="academy_forum_comments")
    op.drop_index("ix_academy_forum_comments_thread_id", table_name="academy_forum_comments")
    op.drop_index("ix_academy_forum_threads_author_persona_id", table_name="academy_forum_threads")
    op.drop_index("ix_academy_forum_threads_course_id", table_name="academy_forum_threads")
    op.drop_index("ix_academy_lessons_course_id", table_name="academy_lessons")
    op.drop_index("ix_accounting_entries_created_by_id", table_name="accounting_entries")
    op.drop_index("ix_admin_audit_logs_actor_persona_id", table_name="admin_audit_logs")
    op.drop_index("ix_agenda_eventos_organizador_persona_id", table_name="agenda_eventos")
    op.drop_index("ix_agenda_eventos_sede_id", table_name="agenda_eventos")
    op.drop_index("ix_agenda_participantes_evento_id", table_name="agenda_participantes")
    op.drop_index("ix_agenda_participantes_persona_id", table_name="agenda_participantes")
    op.drop_index("ix_agenda_recursos_sede_id", table_name="agenda_recursos")
    op.drop_index("ix_agenda_reserva_recursos_evento_id", table_name="agenda_reserva_recursos")
    op.drop_index("ix_agenda_reserva_recursos_recurso_id", table_name="agenda_reserva_recursos")
    op.drop_index("ix_agent_contact_created_by", table_name="agent_contact")
    op.drop_index("ix_agent_insights_acknowledged_by_persona_id", table_name="agent_insights")
    op.drop_index("ix_agent_journey_triggered_by_persona_id", table_name="agent_journey")
    op.drop_index("ix_agent_knowledge_base_indexed_by", table_name="agent_knowledge_base")
    op.drop_index("ix_agent_roles_created_by_persona_id", table_name="agent_roles")
    op.drop_index("ix_agents_created_by_persona_id", table_name="agents")
    op.drop_index("ix_agents_updated_by_persona_id", table_name="agents")
    op.drop_index("ix_auth_password_history_user_id", table_name="auth_password_history")
    op.drop_index("ix_auth_refresh_tokens_user_id", table_name="auth_refresh_tokens")
    op.drop_index("ix_auth_reset_tokens_user_id", table_name="auth_reset_tokens")
    op.drop_index("ix_auth_security_logs_user_id", table_name="auth_security_logs")
    op.drop_index("ix_auth_user_badges_badge_id", table_name="auth_user_badges")
    op.drop_index("ix_auth_user_badges_user_id", table_name="auth_user_badges")
    op.drop_index("ix_auth_user_module_roles_rol_id", table_name="auth_user_module_roles")
    op.drop_index("ix_auth_user_module_roles_user_id", table_name="auth_user_module_roles")
    op.drop_index("ix_auth_users_current_level_id", table_name="auth_users")
    op.drop_index("ix_auth_users_rol_plataforma_id", table_name="auth_users")
    op.drop_index("ix_auth_verification_tokens_user_id", table_name="auth_verification_tokens")
    op.drop_index("ix_bank_reconciliations_created_by_id", table_name="bank_reconciliations")
    op.drop_index("ix_bank_transactions_reconciled_by_id", table_name="bank_transactions")
    op.drop_index("ix_cms_ab_tests_winner_section_id", table_name="cms_ab_tests")
    op.drop_index("ix_cms_content_permissions_created_by_persona_id", table_name="cms_content_permissions")
    op.drop_index("ix_cms_custom_entries_author_persona_id", table_name="cms_custom_entries")
    op.drop_index("ix_cms_custom_entries_owner_persona_id", table_name="cms_custom_entries")
    op.drop_index("ix_cms_custom_entry_versions_created_by_persona_id", table_name="cms_custom_entry_versions")
    op.drop_index("ix_cms_glossary_terms_created_by_persona_id", table_name="cms_glossary_terms")
    op.drop_index("ix_cms_media_file_versions_created_by_persona_id", table_name="cms_media_file_versions")
    op.drop_index("ix_cms_media_folders_created_by_persona_id", table_name="cms_media_folders")
    op.drop_index("ix_cms_media_items_created_by_persona_id", table_name="cms_media_items")
    op.drop_index("ix_cms_notifications_actor_persona_id", table_name="cms_notifications")
    op.drop_index("ix_cms_page_versions_created_by_persona_id", table_name="cms_page_versions")
    op.drop_index("ix_cms_pages_created_by_persona_id", table_name="cms_pages")
    op.drop_index("ix_cms_pages_published_version_id", table_name="cms_pages")
    op.drop_index("ix_cms_pages_updated_by_persona_id", table_name="cms_pages")
    op.drop_index("ix_cms_posts_author_persona_id", table_name="cms_posts")
    op.drop_index("ix_cms_posts_created_by_persona_id", table_name="cms_posts")
    op.drop_index("ix_cms_posts_updated_by_persona_id", table_name="cms_posts")
    op.drop_index("ix_cms_publish_logs_actor_persona_id", table_name="cms_publish_logs")
    op.drop_index("ix_cms_redirects_created_by_persona_id", table_name="cms_redirects")
    op.drop_index("ix_cms_search_index_author_persona_id", table_name="cms_search_index")
    op.drop_index("ix_cms_search_promotions_created_by_persona_id", table_name="cms_search_promotions")
    op.drop_index("ix_cms_sections_created_by_persona_id", table_name="cms_sections")
    op.drop_index("ix_cms_sections_updated_by_persona_id", table_name="cms_sections")
    op.drop_index("ix_cms_themes_created_by_persona_id", table_name="cms_themes")
    op.drop_index("ix_cms_themes_updated_by_persona_id", table_name="cms_themes")
    op.drop_index("ix_cms_webhooks_created_by_persona_id", table_name="cms_webhooks")
    op.drop_index("ix_conversations_last_sender_id", table_name="conversations")
    op.drop_index("ix_crm_casos_origen_estrategia_id", table_name="crm_casos")
    op.drop_index("ix_crm_casos_origen_grupo_id", table_name="crm_casos")
    op.drop_index("ix_crm_casos_origen_sesion_id", table_name="crm_casos")
    op.drop_index("ix_crm_events_form_id", table_name="crm_events")
    op.drop_index("ix_crm_events_target_role_id", table_name="crm_events")
    op.drop_index("ix_crm_interacciones_plantilla_usada_id", table_name="crm_interacciones")
    op.drop_index("ix_crm_pending_actions_automation_id", table_name="crm_pending_actions")
    op.drop_index("ix_documents_uploaded_by_id", table_name="documents")
    op.drop_index("ix_estrategias_evangelismo_default_role_id", table_name="estrategias_evangelismo")
    op.drop_index("ix_event_campaigns_created_by_id", table_name="event_campaigns")
    op.drop_index("ix_event_campaigns_plantilla_id", table_name="event_campaigns")
    op.drop_index("ix_event_identity_challenges_persona_id", table_name="event_identity_challenges")
    op.drop_index("ix_event_registrations_checked_in_by", table_name="event_registrations")
    op.drop_index("ix_expense_receipts_uploaded_by_id", table_name="expense_receipts")
    op.drop_index("ix_expense_reports_approved_by_id", table_name="expense_reports")
    op.drop_index("ix_financial_statements_generated_by_id", table_name="financial_statements")
    op.drop_index("ix_invoice_payments_created_by_id", table_name="invoice_payments")
    op.drop_index("ix_invoices_created_by_id", table_name="invoices")
    op.drop_index("ix_ministries_leader_persona_id", table_name="ministries")
    op.drop_index("ix_persona_ministries_recognized_by_persona_id", table_name="persona_ministries")
    op.drop_index("ix_personas_origen_estrategia_id", table_name="personas")
    op.drop_index("ix_project_activity_logs_persona_id", table_name="project_activity_logs")
    op.drop_index("ix_project_attachments_uploader_id", table_name="project_attachments")
    op.drop_index("ix_project_comments_task_id", table_name="project_comments")
    op.drop_index("ix_project_documents_author_id", table_name="project_documents")
    op.drop_index("ix_sales_orders_created_by_id", table_name="sales_orders")
    op.drop_index("ix_sign_requests_created_by_id", table_name="sign_requests")
    op.drop_index("ix_wiki_page_versions_created_by_persona_id", table_name="wiki_page_versions")
    op.drop_index("ix_wiki_pages_author_id", table_name="wiki_pages")
