"""add_cms_posts_categories_tags

Revision ID: 20260703_0001_add_cms_posts_categories_tags
Revises: 20260702_0002_reported_at_tz
Create Date: 2026-07-03 00:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20260703_0001_add_cms_posts_categories_tags'
down_revision: Union[str, None] = '20260702_0002_reported_at_tz'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cms_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['cms_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'slug', name='uq_cms_category_site_slug')
    )
    with op.batch_alter_table('cms_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cms_categories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_cms_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cms_categories_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cms_categories_slug'), ['slug'], unique=False)

    op.create_table('cms_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('featured_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('seo_json', sa.JSON(), nullable=True),
    sa.Column('locale', sa.String(length=5), server_default='es', nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_persona_id', sa.UUID(), nullable=True),
    sa.Column('created_by_persona_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_persona_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['created_by_persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['cms_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'slug', name='uq_cms_post_site_slug')
    )
    with op.batch_alter_table('cms_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cms_posts_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_cms_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cms_posts_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cms_posts_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_cms_posts_status'), ['status'], unique=False)

    op.create_table('cms_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['cms_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'slug', name='uq_cms_tag_site_slug')
    )
    with op.batch_alter_table('cms_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cms_tags_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_cms_tags_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cms_tags_slug'), ['slug'], unique=False)

    op.create_table('cms_post_categories',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['cms_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['cms_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'category_id')
    )
    op.create_table('cms_post_tags',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['cms_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['cms_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cms_post_tags')
    op.drop_table('cms_post_categories')
    with op.batch_alter_table('cms_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cms_tags_slug'))
        batch_op.drop_index(batch_op.f('ix_cms_tags_site_id'))
        batch_op.drop_index(batch_op.f('ix_cms_tags_is_active'))

    op.drop_table('cms_tags')
    with op.batch_alter_table('cms_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cms_posts_status'))
        batch_op.drop_index(batch_op.f('ix_cms_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_cms_posts_site_id'))
        batch_op.drop_index(batch_op.f('ix_cms_posts_published_at'))
        batch_op.drop_index(batch_op.f('ix_cms_posts_locale'))

    op.drop_table('cms_posts')
    with op.batch_alter_table('cms_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cms_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_cms_categories_site_id'))
        batch_op.drop_index(batch_op.f('ix_cms_categories_parent_id'))
        batch_op.drop_index(batch_op.f('ix_cms_categories_is_active'))

    op.drop_table('cms_categories')
    # ### end Alembic commands ###
