"""
CCF Backend — CRUD operations split by domain.

Each sub-module contains the data-access functions for one business area.
This package re-exports everything so that existing callers using
``from backend import crud`` / ``crud.function_name(...)`` continue to work.
"""

# Utils
from backend.crud._utils import (  # noqa: F401
    _utcnow,
    analyze_pastoral_priority,
    analyze_pastoral_sentiment,
)

# Identity & auth
from backend.crud.identity import (  # noqa: F401
    get_user,
    get_user_by_email,
    get_user_by_username,
    get_users,
    create_user,
    update_user,
    delete_user,
    create_refresh_token,
    get_valid_refresh_token,
    revoke_refresh_token,
    create_verification_token,
    use_verification_token,
    create_reset_token,
    use_reset_token,
    grant_xp,
    award_badge,
    update_ui_preferences,
    get_ui_preferences,
    ensure_ui_preferences,
)

# Academy
from backend.crud.academy import (  # noqa: F401
    get_courses,
    get_course,
    create_course,
    update_course,
    delete_course,
    get_course_students,
    check_user_meets_prerequisites,
    get_lessons_by_course,
    get_lesson,
    create_lesson,
    update_lesson,
    delete_lesson,
    get_enrollment,
    get_enrollment_by_user_course,
    get_enrollments_by_user,
    create_enrollment,
    update_enrollment,
    delete_enrollment,
    get_assessment,
    get_assessment_by_id,
    get_assessment_with_questions,
    get_assessments_by_course,
    create_assessment,
    update_assessment,
    delete_assessment,
    get_assessment_questions,
    get_assessment_question,
    create_assessment_question,
    update_assessment_question,
    delete_assessment_question,
    get_assessment_options,
    create_assessment_option,
    update_assessment_option,
    delete_assessment_option,
    create_or_update_assessment_attempt,
    submit_assessment_attempt,
    get_lesson_progress,
    update_lesson_progress,
    get_certificates_by_user,
    get_certificate,
    get_certificate_by_code,
    issue_certificate_for_enrollment,
    issue_certificate,
    issue_pending_certificates,
    delete_certificate,
    close_formal_acta,
    get_latest_acta_by_course,
    record_activity_attendance,
    get_course_attendance,
    create_course_attendance,
    delete_course_attendance,
    get_lesson_resources,
    create_resource,
    delete_resource,
    create_assignment_submission,
    list_assignment_submissions_with_meta,
    get_assignment_submission_with_meta,
    grade_assignment_submission,
    get_academy_candidates,
    get_forum_threads,
    get_forum_thread,
    create_forum_thread,
    delete_forum_thread,
)

# CRM
from backend.crud.crm import (  # noqa: F401
    get_member,
    create_member,
    search_members,
    get_members,
    update_member,
    delete_member,
    get_member_donations,
    get_member_timeline,
    get_pipeline_lead,
    get_pipeline_leads,
    create_pipeline_lead,
    update_pipeline_lead,
    delete_pipeline_lead,
    get_pastoral_call_log,
    create_pastoral_call_log,
    get_pastoral_call_logs,
    delete_pastoral_call_log,
    get_crm_event,
    get_crm_events,
    create_crm_event,
    update_crm_event,
    delete_crm_event,
    get_event_attendance,
    create_event_attendance,
    delete_event_attendance,
    get_crm_tasks,
    create_crm_task,
    update_crm_task,
    delete_crm_task,
    get_volunteer_shift,
    get_volunteer_shifts,
    create_volunteer_shift,
    update_volunteer_shift,
    delete_volunteer_shift,
    get_counseling_ticket,
    get_counseling_tickets,
    create_counseling_ticket,
    update_counseling_ticket,
    delete_counseling_ticket,
    get_prayer_request,
    get_prayer_requests,
    create_prayer_request,
    update_prayer_request,
    delete_prayer_request,
    get_glory_house,
    get_glory_houses,
    create_glory_house,
    update_glory_house,
    delete_glory_house,
    get_talents,
    get_family,
    get_families,
    create_family,
    update_family,
    delete_family,
    get_family_members,
    get_communication_log,
    create_communication_log,
    get_communication_logs,
    update_communication_log,
    delete_communication_log,
    get_user_notifications,
    mark_notification_as_read,
    mark_all_notifications_read,
    get_donation,
    create_donation,
    get_donations,
    update_donation,
    delete_donation,
    get_total_donations_amount,
    get_milestones,
    create_milestone,
    update_milestone,
    delete_milestone,
    get_support_ticket,
    create_support_ticket,
    get_support_tickets,
    update_support_ticket,
    delete_support_ticket,
    get_community_card,
    get_community_cards,
    create_community_card,
    update_community_card,
    delete_community_card,
    get_evangelism_strategies,
    create_evangelism_strategy,
    update_evangelism_strategy,
    delete_evangelism_strategy,
    get_consolidation_case,
    create_consolidation_case,
    update_consolidation_case,
    delete_consolidation_case,
)

# CRM Extended — roles, positions, ministries, funds, skills, automations, chat
from backend.crud.crm_extended import (  # noqa: F401
    # Positions
    get_positions,
    get_position,
    create_position,
    update_position,
    delete_position,
    PositionCreate,
    PositionUpdate,
    # Member Positions
    get_member_positions,
    get_member_position,
    create_member_position,
    update_member_position,
    delete_member_position,
    MemberPositionCreate,
    MemberPositionUpdate,
    # Event Assignments
    get_event_assignments,
    get_event_assignment,
    create_event_assignment,
    update_event_assignment,
    delete_event_assignment,
    EventAssignmentCreate,
    EventAssignmentUpdate,
    # Ministries
    get_ministries,
    get_ministry,
    create_ministry,
    update_ministry,
    delete_ministry,
    MinistryCreate,
    MinistryUpdate,
    # Member Ministries
    get_member_ministries,
    get_member_ministry,
    create_member_ministry,
    update_member_ministry,
    delete_member_ministry,
    MemberMinistryCreate,
    MemberMinistryUpdate,
    # CRM Automations
    get_crm_automations,
    get_crm_automation,
    create_crm_automation,
    update_crm_automation,
    delete_crm_automation,
    CrmAutomationCreate,
    CrmAutomationUpdate,
    # Role Definitions
    get_role_definitions,
    get_role_definition,
    create_role_definition,
    update_role_definition,
    delete_role_definition,
    RoleDefinitionCreate,
    RoleDefinitionUpdate,
    # Member Roles
    get_member_roles,
    create_member_role,
    delete_member_role,
    MemberRoleCreate,
    # Funds
    get_funds,
    get_fund,
    create_fund,
    update_fund,
    delete_fund,
    FundCreate,
    FundUpdate,
    # Volunteer Skills
    get_volunteer_skills,
    get_volunteer_skill,
    create_volunteer_skill,
    update_volunteer_skill,
    delete_volunteer_skill,
    VolunteerSkillCreate,
    VolunteerSkillUpdate,
    # Chat Messages
    get_chat_messages,
    get_chat_message,
    create_chat_message,
    delete_chat_message,
    ChatMessageCreate,
)

# Consolidation Extended — assignments, interactions, follow-up tasks
from backend.crud.consolidation import (  # noqa: F401
    get_consolidation_assignments,
    get_consolidation_assignment,
    create_consolidation_assignment,
    update_consolidation_assignment,
    delete_consolidation_assignment,
    get_consolidation_interactions,
    get_consolidation_interaction,
    create_consolidation_interaction,
    update_consolidation_interaction,
    delete_consolidation_interaction,
    get_consolidation_follow_up_tasks,
    get_consolidation_follow_up_task,
    create_consolidation_follow_up_task,
    update_consolidation_follow_up_task,
    delete_consolidation_follow_up_task,
)

# CMS
from backend.crud.cms import (  # noqa: F401
    update_page_content,
    get_page_content,
    list_page_contents,
    get_or_create_page_content,
    get_page_content_versions,
    restore_page_content_version,
    get_or_create_content_publication,
    update_content_publication,
    list_content_publications,
    create_cms_media_item,
    list_cms_media_items,
    get_cms_media_item,
    update_cms_media_item,
    delete_cms_media_item,
    create_media_asset,
    delete_media_asset,
    increment_content_metric,
    list_cms_sites,
    get_cms_site_by_key,
    create_cms_site,
    update_cms_site,
    archive_cms_site,
    list_cms_themes,
    create_cms_theme,
    get_cms_theme,
    update_cms_theme,
    activate_cms_theme,
    archive_cms_theme,
    get_active_cms_theme,
    list_cms_menus,
    get_cms_menu,
    create_cms_menu,
    update_cms_menu,
    delete_cms_menu,
    list_cms_menu_items,
    create_cms_menu_item,
    get_cms_menu_item,
    update_cms_menu_item,
    delete_cms_menu_item,
    reorder_cms_menu_items,
    list_cms_pages,
    get_cms_page,
    create_cms_page,
    update_cms_page,
    delete_cms_page,
    list_cms_sections,
    create_cms_section,
    get_cms_section,
    update_cms_section,
    delete_cms_section,
    archive_cms_section,
    reorder_cms_sections,
    create_cms_page_version,
    list_cms_page_versions,
    get_cms_page_version,
    list_cms_publish_logs,
    restore_cms_page_version,
    transition_cms_page_status,
    get_public_cms_page,
    create_announcement,
    list_announcements,
    get_announcement,
    update_announcement,
    delete_announcement,
    create_testimonial,
    list_testimonials,
    get_testimonial,
    update_testimonial,
    delete_testimonial,
)

# Agents
from backend.crud.agents import (  # noqa: F401
    create_agent_task,
    list_agent_tasks,
    update_agent_task,
    delete_agent_task,
    create_agent_insight,
    list_agent_insights,
    acknowledge_insight,
    delete_agent_insight,
)

# Audit
from backend.crud.audit import (  # noqa: F401
    create_admin_audit_log,
    get_admin_audit_logs,
)

# Governance
from backend.crud.governance import (  # noqa: F401
    get_automation_rules,
    get_automation_rule,
    create_automation_rule,
    update_automation_rule,
    delete_automation_rule,
    record_automation_run,
)

# Dashboard
from backend.crud.dashboard import (  # noqa: F401
    get_dashboard_metrics,
    get_pastor_radar,
    get_pilot_readiness,
    search_knowledge_base,
)

# Projects
from backend.crud.projects import (  # noqa: F401
    create_project,
    get_projects,
    get_project,
    update_project,
    delete_project,
    create_project_task,
    get_project_tasks,
    get_project_task,
    update_project_task,
    delete_project_task,
    get_project_phases,
    set_project_phases,
    create_default_phases,
    get_project_comments,
    get_comment,
    create_comment,
    update_comment,
    delete_comment,
    get_project_milestones,
    get_milestone,
    create_milestone,
    update_milestone,
    delete_milestone,
    get_task_attachments,
    get_attachment,
    create_attachment,
    delete_attachment,
    get_project_whiteboard,
    update_project_whiteboard,
    get_project_wiki,
    update_project_wiki,
    get_task_supplies,
    get_supply,
    create_supply,
    update_supply,
    delete_supply,
    get_project_activities,
    create_activity_log,
    get_inbox_state,
    update_inbox_state,
    get_portfolio_summary,
    get_workload_summary,
)

# Assets
from backend.crud.assets import (  # noqa: F401
    get_assets,
    get_asset,
    create_asset,
    update_asset,
    delete_asset,
    get_maintenance_logs,
    create_maintenance_log,
)

# Ops — church locations, social channels, system variables
from backend.crud.ops import (  # noqa: F401
    get_church_locations,
    get_church_location,
    create_church_location,
    update_church_location,
    delete_church_location,
    get_social_channels,
    get_social_channel,
    create_social_channel,
    update_social_channel,
    delete_social_channel,
    get_system_variables,
    get_system_variable,
    get_system_variable_value,
    create_system_variable,
    update_system_variable,
    upsert_system_variable,
    delete_system_variable,
    ChurchLocationCreate,
    ChurchLocationUpdate,
    SocialChannelCreate,
    SocialChannelUpdate,
    SystemVariableCreate,
    SystemVariableUpdate,
)
