import uuid

from fastapi import FastAPI, HTTPException
from fastapi.testclient import TestClient

# Import the router and helper functions
from backend.api import cms_v2 as cms

# Helper to create a FastAPI app with the router and overridden deps

def create_app(monkeypatch):
    app = FastAPI()
    app.include_router(cms.router)

    # Override DB dependency to provide a dummy object
    # After router inclusion, replace each auth dependency (generated by require_module_access) with a stub that returns a dummy user.
    def _override_auth_deps(app_instance):
        from fastapi.routing import APIRoute
        class DummyUser:
            id = uuid.uuid4()
            role = "admin"
            rol_plataforma = None
        for route in getattr(app_instance, "router").routes:
            if isinstance(route, APIRoute):
                for dep in getattr(route, "dependant").dependencies:
                    # The auth dependency is the inner function produced by require_permission
                    if callable(dep.call):
                        def _dummy_user(*args, **kwargs):
                            return DummyUser()
                        app_instance.dependency_overrides[dep.call] = _dummy_user
    
    # Apply auth overrides
    _override_auth_deps(app)
    class DummyDB:
        pass

    def get_db_override():
        return DummyDB()

    app.dependency_overrides[cms.get_db] = get_db_override

    # Override permission dependency to bypass auth
    def require_module_access_override(*args, **kwargs):
        # Return a dummy user object with required attributes
        class DummyUser:
            id = uuid.uuid4()
            role = "admin"
            # emulate rol_plataforma for legacy compatibility
            rol_plataforma = None
        return DummyUser()

    app.dependency_overrides[cms.require_module_access] = require_module_access_override
    app.dependency_overrides[cms.normalize_role] = lambda r: r.lower().strip() if r else ""

    return app


def test_slugify():
    # Basic slugify behavior
    assert cms._slugify("  Hello World  ") == "hello-world"
    # Removes illegal characters
    assert cms._slugify("My@Page!#") == "mypage"
    # Keeps underscores and slashes
    assert cms._slugify("/path/to/resource_") == "/path/to/resource_"

def test_assert_role_success(monkeypatch):
    # Create a dummy user with role admin
    class DummyUser:
        role = "admin"
        rol_plataforma = None
    # Should not raise
    cms._assert_role(DummyUser(), {"admin", "editor"})

def test_assert_role_fallback(monkeypatch):
    class DummyUser:
        role = ""
        class rol_plataforma:
            nombre = "Coordinador"
    # Should not raise for allowed role
    cms._assert_role(DummyUser(), {"coordinador"})
    # Disallowed role raises HTTPException
    try:
        cms._assert_role(DummyUser(), {"admin"})
        assert False, "Expected HTTPException"
    except HTTPException as exc:
        assert exc.status_code == 403

def test_list_sites(monkeypatch):
    # Mock crud.list_cms_sites
    mock_sites = [{"site_key": "default", "is_active": True}]
    monkeypatch.setattr(cms.crud, "list_cms_sites", lambda db, only_active=False: mock_sites)

    app = create_app(monkeypatch)
    client = TestClient(app)
    response = client.get("/cms/v2/sites")
    assert response.status_code == 200
    assert response.json() == mock_sites

def test_create_site_success(monkeypatch):
    payload = {"site_key": "newsite", "base_path": "/new", "name": "New Site"}
    created = {**payload, "id": str(uuid.uuid4())}
    # Mock helpers
    monkeypatch.setattr(cms.crud, "get_cms_site_by_key", lambda db, key: None)
    monkeypatch.setattr(cms.crud, "create_cms_site", lambda db, p: created)
    monkeypatch.setattr(cms, "_assert_role", lambda user, roles, detail="": None)

    app = create_app(monkeypatch)
    client = TestClient(app)
    response = client.post("/cms/v2/sites", json=payload)
    assert response.status_code == 201
    assert response.json()["site_key"] == "newsite"

def test_get_site_not_found(monkeypatch):
    # Mock get_cms_site_by_key to return None
    monkeypatch.setattr(cms.crud, "get_cms_site_by_key", lambda db, key: None)
    app = create_app(monkeypatch)
    client = TestClient(app)
    response = client.get("/cms/v2/sites/nonexistent")
    assert response.status_code == 404
    assert response.json()["detail"] == "site not found"

def test_create_theme_blocked(monkeypatch):
    # Simulate a user without publisher role trying to activate a theme
    payload = {"name": "test", "is_active": True}
    # Mock role check to raise
    def fake_assert(user, allowed, detail=""):
        raise HTTPException(status_code=403, detail=detail)
    monkeypatch.setattr(cms, "_assert_role", fake_assert)
    # Mock site retrieval
    dummy_site = type("S", (), {"id": uuid.uuid4()})
    monkeypatch.setattr(cms, "_get_site_or_404", lambda db, key: dummy_site)

    app = create_app(monkeypatch)
    client = TestClient(app)
    response = client.post("/cms/v2/sites/default/themes", json=payload)
    assert response.status_code == 403

# Additional sanity test for internal helper _get_system_var
def test_get_system_var(monkeypatch):
    class DummyRow:
        def __init__(self, value):
            self.value = value
    class DummyDB:
        def query(self, model):
            return self
        def filter(self, *args, **kwargs):
            return self
        def first(self):
            return DummyRow("value")
    db = DummyDB()
    result = cms._get_system_var(db, "mysite", "key")
    assert result == "value"
