import uuid
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException
from fastapi.testclient import TestClient

import backend.api.cms.admin.sites as admin_sites
import backend.api.cms.admin.themes as admin_themes
import backend.crud as backend_crud

# Import the router and helper functions
from backend.api import cms_v2 as cms
from backend.api.cms_v2._shared import normalize_role
from backend.core.database import get_db
from backend.core.permissions import get_current_user, require_module_access
from backend.exceptions.cms import CmsPermissionError

# Helper to create a FastAPI app with the router and overridden deps


def create_app(monkeypatch):
    app = FastAPI()
    app.include_router(cms.router)
    monkeypatch.setattr(cms, "_actor_sede_from_user", lambda db, current_user: None)

    # Override DB dependency to provide a dummy object
    # After router inclusion, replace each auth dependency (generated by require_module_access) with a stub that returns a dummy user.
    def _override_auth_deps(app_instance):
        from fastapi.routing import APIRoute

        class DummyUser:
            id = uuid.uuid4()
            role = "admin"
            rol_plataforma = None
            is_active = True
            permissions = {"cms:read": "allow", "cms:edit": "allow", "cms:manage": "allow"}

        for route in getattr(app_instance, "router").routes:
            if isinstance(route, APIRoute):
                for dep in getattr(route, "dependant").dependencies:
                    # The auth dependency is the inner function produced by require_permission
                    if callable(dep.call):

                        def _dummy_user():
                            return DummyUser()

                        app_instance.dependency_overrides[dep.call] = _dummy_user

    # Apply auth overrides
    _override_auth_deps(app)

    class DummyUserInstance:
        id = uuid.uuid4()
        role = "admin"
        rol_plataforma = None
        is_active = True
        permissions = {"cms:read": "allow", "cms:edit": "allow", "cms:manage": "allow"}

    app.dependency_overrides[get_current_user] = lambda: DummyUserInstance()

    class DummyDB:
        def query(self, *args, **kwargs):
            return self
        def filter(self, *args, **kwargs):
            return self
        def options(self, *args, **kwargs):
            return self
        def order_by(self, *args, **kwargs):
            return self
        def first(self, *args, **kwargs):
            return None
        def scalar(self, *args, **kwargs):
            return None
        def update(self, *args, **kwargs):
            return 0
        def all(self, *args, **kwargs):
            return []
        def add(self, *args, **kwargs):
            pass
        def commit(self, *args, **kwargs):
            pass
        def flush(self, *args, **kwargs):
            pass
        def refresh(self, obj, *args, **kwargs):
            if hasattr(obj, "id") and getattr(obj, "id") is None:
                obj.id = uuid.uuid4()
            if hasattr(obj, "created_at") and getattr(obj, "created_at") is None:
                obj.created_at = datetime.now(timezone.utc)
            if hasattr(obj, "updated_at") and getattr(obj, "updated_at") is None:
                obj.updated_at = datetime.now(timezone.utc)

    def get_db_override():
        return DummyDB()

    app.dependency_overrides[get_db] = get_db_override

    # Override permission dependency to bypass auth
    def require_module_access_override(*args, **kwargs):
        # Return a dummy user object with required attributes
        class DummyUser:
            id = uuid.uuid4()
            role = "admin"
            # emulate rol_plataforma for old compatibility
            rol_plataforma = None
            is_active = True
            permissions = {"cms:read": "allow", "cms:edit": "allow", "cms:manage": "allow"}

        return DummyUser()

    app.dependency_overrides[require_module_access] = require_module_access_override
    app.dependency_overrides[normalize_role] = lambda r: r.lower().strip() if r else ""

    from fastapi import Request
    from fastapi.responses import JSONResponse

    from backend.exceptions.cms import CmsError

    @app.exception_handler(CmsError)
    async def cms_exception_handler(request: Request, exc: CmsError):
        return JSONResponse(status_code=exc.status_code, content=exc.to_dict())

    return app


def test_slugify():
    # Basic slugify behavior
    assert cms._slugify("  Hello World  ") == "hello-world"
    # Removes illegal characters
    assert cms._slugify("My@Page!#") == "mypage"
    # Keeps underscores and slashes
    assert cms._slugify("/path/to/resource_") == "/path/to/resource_"


def test_assert_role_success(monkeypatch):
    # Create a dummy user with role admin
    class DummyUser:
        role = "admin"
        rol_plataforma = None

    # Should not raise
    cms._assert_role(DummyUser(), {"admin", "editor"})


def test_assert_role_fallback(monkeypatch):
    class DummyUser:
        role = ""

        class rol_plataforma:
            nombre = "Coordinador"

    # Should not raise for allowed role
    cms._assert_role(DummyUser(), {"coordinador"})
    # Disallowed role raises CmsPermissionError
    try:
        cms._assert_role(DummyUser(), {"admin"})
        assert False, "Expected CmsPermissionError"
    except CmsPermissionError as exc:
        assert exc.status_code == 403


def test_list_sites(monkeypatch):
    # Mock crud.list_cms_sites
    now = datetime.now(timezone.utc)
    mock_sites = [
        {
            "id": str(uuid.uuid4()),
            "site_key": "default",
            "name": "Default",
            "base_path": "/",
            "is_active": True,
            "created_at": now,
            "updated_at": now,
        }
    ]
    monkeypatch.setattr(
        backend_crud,
        "list_cms_sites",
        lambda db, only_active=False, sede_id=None: mock_sites,
    )

    app = create_app(monkeypatch)
    client = TestClient(app)
    response = client.get("/cms/v2/sites")
    assert response.status_code == 200
    data = response.json()
    assert data[0]["site_key"] == mock_sites[0]["site_key"]
    assert data[0]["is_active"] is True


def test_create_site_success(monkeypatch):
    now = datetime.now(timezone.utc)
    payload = {"site_key": "newsite", "base_path": "/new", "name": "New Site"}
    created = {
        **payload,
        "id": str(uuid.uuid4()),
        "is_active": True,
        "created_at": now,
        "updated_at": now,
    }
    # Mock helpers
    monkeypatch.setattr(backend_crud, "get_cms_site_by_key", lambda db, key: None)
    monkeypatch.setattr(backend_crud, "create_cms_site", lambda db, p, *args, **kwargs: created)
    monkeypatch.setattr(admin_sites, "_assert_role", lambda user, roles, detail="": None)

    app = create_app(monkeypatch)
    client = TestClient(app)
    response = client.post("/cms/v2/sites", json=payload)
    assert response.status_code == 201
    assert response.json()["site_key"] == "newsite"


def test_get_site_not_found(monkeypatch):
    # Mock get_cms_site_by_key to return None
    monkeypatch.setattr(backend_crud, "get_cms_site_by_key", lambda db, key: None)
    app = create_app(monkeypatch)
    client = TestClient(app)
    response = client.get("/cms/v2/sites/nonexistent")
    assert response.status_code == 404
    assert response.json()["detail"] == "Site not found"


def test_create_theme_blocked(monkeypatch):
    # Simulate a user without publisher role trying to activate a theme
    payload = {"name": "test", "is_active": True}

    # Mock role check to raise
    def fake_assert(user, allowed, detail=""):
        raise HTTPException(status_code=403, detail=detail)

    monkeypatch.setattr(admin_themes, "_assert_role", fake_assert)
    # Mock site retrieval
    dummy_site = type("S", (), {"id": uuid.uuid4(), "site_key": "default"})
    monkeypatch.setattr(backend_crud, "get_cms_site_by_key", lambda db, key: dummy_site)

    app = create_app(monkeypatch)
    client = TestClient(app)
    response = client.post("/cms/v2/sites/default/themes", json=payload)
    assert response.status_code == 403


# Additional sanity test for internal helper _get_system_var
def test_get_system_var(monkeypatch):
    class DummyRow:
        def __init__(self, value):
            self.value = value

    class DummyDB:
        def query(self, model):
            return self

        def filter(self, *args, **kwargs):
            return self

        def first(self):
            return DummyRow("value")

    db = DummyDB()
    result = cms._get_system_var(db, "mysite", "key")
    assert result == "value"
