{{- if .Values.backend.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-backend-secrets" (include "ccf.fullname" .) | quote }}
type: Opaque
stringData:
  {{ .Values.backend.secrets.secretKeyKey }}: {{ .Values.backend.secrets.secretKey | quote }}
  {{ .Values.backend.secrets.encryptionKeyKey }}: {{ .Values.backend.secrets.encryptionKey | quote }}
{{- end }}
