apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-backend" (include "ccf.fullname" .) | quote }}
  labels:
    app.kubernetes.io/name: {{ include "ccf.name" . | quote }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ccf.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 8000
