from __future__ import annotations

from backend.schemas._common import PaginatedResponse, orm_config

# ── Academy / LMS ────────────────────────────────────────────────────────────
from backend.schemas.academy import (
                                     AcademyStudentProfile,
                                     Assessment,
                                     AssessmentAttempt,
                                     AssessmentAttemptSubmit,
                                     AssessmentOption,
                                     AssessmentQuestion,
                                     AssignmentSubmission,
                                     AssignmentSubmissionReview,
                                     Attendance,
                                     BulkAttendanceCreate,
                                     BulkAttendanceRecord,
                                     Certificate,
                                     ChatMessage,
                                     Course,
                                     CourseAttendance,
                                     CourseAttendanceBase,
                                     CourseAttendanceCreate,
                                     CoursePrerequisite,
                                     CoursePrerequisiteBase,
                                     DashboardMetrics,
                                     Enrollment,
                                     EnrollmentCreate,
                                     FormalActa,
                                     FormalActaCloseRequest,
                                     ForumThread,
                                     ForumThreadBase,
                                     ForumThreadCreate,
                                     Lesson,
                                     PilotReadiness,
                                     Resource,
)
from backend.schemas.agenda import AgendaEvent, AgendaEventCreate

# ── Agents ───────────────────────────────────────────────────────────────────
from backend.schemas.agents import AgentInsight, AgentInsightCreate, AgentTask, AgentTaskCreate, AgentTaskUpdate

# ── Auth v3 ──────────────────────────────────────────────────────────────────
from backend.schemas.auth_v3 import (
                                     AuthStatsSummary,
                                     CambioPasswordRequest,
                                     ForgotPasswordRequest,
                                     LogSeguridadRead,
                                     MedallaCreate,
                                     MedallaRead,
                                     MedallaUsuarioRead,
                                     MfaRecoveryResponse,
                                     MfaSetupResponse,
                                     MfaVerifyRequest,
                                     NivelGamificadoBase,
                                     NivelGamificadoCreate,
                                     NivelGamificadoRead,
                                     NotificacionRead,
                                     PreferenciaUIRead,
                                     PreferenciaUIUpdate,
                                     RecordatorioCreate,
                                     RecordatorioRead,
                                     ResetPasswordRequest,
                                     RolPlataformaBase,
                                     RolPlataformaCreate,
                                     RolPlataformaRead,
                                     RolPlataformaUpdate,
                                     TokenResponse,
                                     TokenSesionRead,
                                     UsuarioBase,
                                     UsuarioCreate,
                                     UsuarioLogin,
                                     UsuarioRead,
                                     UsuarioRolModuloBase,
                                     UsuarioRolModuloCreate,
                                     UsuarioRolModuloRead,
                                     UsuarioSelfUpdate,
                                     UsuarioUpdate,
)
from backend.schemas.auth_v3 import (
                                     RefreshTokenRequest as AuthRefreshTokenRequest,
)

# ── Chat / Direct Messages ───────────────────────────────────────────
from backend.schemas.chat import (
                                     ConversationCreate,
                                     ConversationParticipantRead,
                                     ConversationRead,
                                     DirectMessageCreate,
                                     DirectMessageItem,
)

# ── CMS ──────────────────────────────────────────────────────────────────────
from backend.schemas.cms import (
                                     AnnouncementCreate,
                                     AnnouncementRead,
                                     AnnouncementUpdate,
                                     CmsMediaCreate,
                                     CmsMediaRead,
                                     CmsMediaUpdate,
                                     CmsMenuCreate,
                                     CmsMenuItemCreate,
                                     CmsMenuItemRead,
                                     CmsMenuItemReorderItem,
                                     CmsMenuItemReorderPayload,
                                     CmsMenuItemUpdate,
                                     CmsMenuRead,
                                     CmsMenuUpdate,
                                     CmsMetrics,
                                     CmsPageCreate,
                                     CmsPageRead,
                                     CmsPageUpdate,
                                     CmsPageVersionRead,
                                     CmsPublicPageRead,
                                     CmsPublishLogRead,
                                     CmsSectionCreate,
                                     CmsSectionRead,
                                     CmsSectionReorderItem,
                                     CmsSectionReorderPayload,
                                     CmsSectionUpdate,
                                     CmsSiteCreate,
                                     CmsSiteRead,
                                     CmsSiteUpdate,
                                     CmsThemeCreate,
                                     CmsThemeRead,
                                     CmsThemeUpdate,
                                     CmsWorkflowAction,
                                     ContentWorkflowRead,
                                     ContentWorkflowUpdate,
                                     NewsletterSubscriptionCreate,
                                     NewsletterSubscriptionRead,
                                     PageContentRead,
                                     PageContentUpdate,
                                     PageContentVersionRead,
                                     PastoralProfileRead,
                                     PastoralProfileUpdate,
                                     TestimonialAuthorRead,
                                     TestimonialCreate,
                                     TestimonialRead,
                                     TestimonialUpdate,
)
from backend.schemas.crm import (
                                     EVENT_TYPES,
                                     MINISTRY_ROLES,
                                     CaseCall,
                                     CaseCallCreate,
                                     CaseInteractionCreate,
                                     CaseTaskCreate,
                                     CaseTaskUpdate,
                                     CaseUpdate,
                                     ColombianCity,
                                     ColombianDepartment,
                                     CounselingTicket,
                                     CounselingTicketBase,
                                     CounselingTicketCreate,
                                     CounselingTicketUpdate,
                                     CrmEvent,
                                     CrmEventBase,
                                     CrmEventCreate,
                                     CrmEventUpdate,
                                     CrmTask,
                                     CrmTaskBase,
                                     CrmTaskCreate,
                                     CrmTaskUpdate,
                                     Donation,
                                     DonationBase,
                                     DonationCreate,
                                     DonationUpdate,
                                     EvangelismStrategy,
                                     EvangelismStrategyBase,
                                     EvangelismStrategyCreate,
                                     EvangelismStrategyUpdate,
                                     EventAttendance,
                                     EventAttendanceBase,
                                     EventAttendanceCreate,
                                     EventAudienceType,
                                     EventType,
                                     Family,
                                     FaroAttendanceReportItem,
                                     FaroSessionAttendance,
                                     FaroSessionAttendanceItem,
                                     FaroSessionReportUpdate,
                                     FormationLevel,
                                     FormationLevelBase,
                                     FormationLevelCreate,
                                     FormationLevelUpdate,
                                     Persona,
                                     PersonaCreate,
                                     PersonaEvangelism,
                                     PersonaEvangelismBase,
                                     PersonaEvangelismCreate,
                                     PersonaEvangelismUpdate,
                                     PersonaFormation,
                                     PersonaFormationBase,
                                     PersonaFormationCreate,
                                     PersonaFormationUpdate,
                                     PersonaMinistryAssignment,
                                     PersonaMinistryAssignmentBase,
                                     PersonaMinistryAssignmentCreate,
                                     PersonaMinistryAssignmentUpdate,
                                     PersonaPosition,
                                     PersonaPositionBase,
                                     PersonaPositionCreate,
                                     PersonaPositionUpdate,
                                     PersonaResponse,
                                     PersonaSelfProfileUpdate,
                                     PersonaUpdate,
                                     Position,
                                     PositionBase,
                                     PositionCreate,
                                     PositionUpdate,
                                     PrayerRequest,
                                     PrayerRequestBase,
                                     PrayerRequestCreate,
                                     PrayerRequestPublicCreate,
                                     PrayerRequestUpdate,
                                     TeachingAssignment,
                                     TeachingAssignmentBase,
                                     TeachingAssignmentCreate,
                                     TeachingAssignmentUpdate,
                                     VolunteerShift,
                                     VolunteerShiftBase,
                                     VolunteerShiftCreate,
                                     VolunteerShiftUpdate,
)

# ── CRM Resources (Biblioteca de Recursos) ───────────────────────────
from backend.schemas.crm_resources import (  # noqa: F401
                                     BitacoraEnvioOut,
                                     CategoriaRecursoCreate,
                                     CategoriaRecursoOut,
                                     CategoriaRecursoUpdate,
                                     EnviarPlantillaPayload,
                                     PlantillaMensajeCreate,
                                     PlantillaMensajeOut,
                                     PlantillaMensajeUpdate,
                                     RecursoAdjuntoOut,
)

# ── Dashboard & Analytics ───────────────────────────────────────────────────
from backend.schemas.dashboard import (
                                     AcademyDashboard,
                                     AdminGlobalDashboard,
                                     ChartDataPoint,
                                     CrmDashboard,
                                     FinanceDashboard,
                                     MetricCard,
                                     ProjectsDashboard,
)

# ── CRM / Pastoral ───────────────────────────────────────────────────────────
# ── Evangelism (refactor) ────────────────────────────────────────────────────
from backend.schemas.evangelism import (
                                     AsistenciaBulkCreate,
                                     AsistenciaBulkItem,
                                     AsistenciaGrupoCreate,
                                     AsistenciaSesionBase,
                                     AsistenciaSesionCreate,
                                     AsistenciaSesionResponse,
                                     AsistenciaSesionUpdate,
                                     ClaseEstrategiaEnum,
                                     EstadoAsistenciaEnum,
                                     EstadoSesionEnum,
                                     EstrategiaEvangelismoBase,
                                     EstrategiaEvangelismoCreate,
                                     EstrategiaEvangelismoResponse,
                                     EstrategiaEvangelismoUpdate,
                                     FrecuenciaEnum,
                                     GrupoEvangelismoCreate,
                                     GrupoEvangelismoUpdate,
                                     MotivoExcusaBase,
                                     MotivoExcusaCreate,
                                     MotivoExcusaResponse,
                                     MotivoExcusaUpdate,
                                     ParticipanteGrupoBase,
                                     ParticipanteGrupoConRol,
                                     ParticipanteGrupoCreate,
                                     ParticipanteGrupoResponse,
                                     ParticipanteGrupoUpdate,
                                     RegistroSeguimientoBase,
                                     RegistroSeguimientoCreate,
                                     RegistroSeguimientoResponse,
                                     RegistroSeguimientoUpdate,
                                     RolEnGrupoEnum,
                                     RolPersonalizadoEstrategiaBase,
                                     RolPersonalizadoEstrategiaCreate,
                                     RolPersonalizadoEstrategiaResponse,
                                     SesionGrupoCreate,
                                     SesionGrupoUpdate,
                                     TipoSeguimientoEnum,
)

# ── Governance / Audit ───────────────────────────────────────────────────────
from backend.schemas.governance import AdminAuditLog, AutomationRuleCreate, AutomationRuleRead, AutomationRuleUpdate

# ── Identity & Auth ──────────────────────────────────────────────────────────
from backend.schemas.identity import (
                                     RefreshTokenRequest,
                                     Role,
                                     RoleBase,
                                     RoleCreate,
                                     Token,
                                     TokenUser,
                                     User,
                                     UserBase,
                                     UserCreate,
                                     UserSelfUpdate,
                                     UserUpdate,
)

# ── Notifications / Comms ────────────────────────────────────────────────────
from backend.schemas.notifications import CommunicationLog, CommunicationLogCreate, CommunicationLogUpdate, Notification

# ── Operational / Misc ───────────────────────────────────────────────────────
from backend.schemas.operational import (
                                     CommunityBoardCard,
                                     CommunityBoardCardCreate,
                                     CommunityBoardCardUpdate,
                                     Milestone,
                                     MilestoneCreate,
                                     PastorRadarSchema,
                                     PublicRegistrationCreate,
                                     SupportTicket,
                                     SupportTicketCreate,
)

# ── Projects ─────────────────────────────────────────────────────────────────
# ── Projects (canonical) ────────────────────────────────────────────────────
from backend.schemas.projects import (  # noqa: F401
                                     InboxReadToggle,
                                     Project,
                                     ProjectActivityItem,
                                     ProjectActivityLog,
                                     ProjectAttachment,
                                     ProjectBase,
                                     ProjectCommentBase,
                                     ProjectCommentCreate,
                                     ProjectCommentItem,
                                     ProjectCommentUpdate,
                                     ProjectCreate,
                                     ProjectDocument,
                                     ProjectDocumentUpdate,
                                     ProjectInboxItem,
                                     ProjectMessageCreate,
                                     ProjectMessageItem,
                                     ProjectMilestone,
                                     ProjectMilestoneBase,
                                     ProjectMilestoneUpdate,
                                     ProjectPhaseInput,
                                     ProjectPhaseSchema,
                                     ProjectPortfolioSummaryRow,
                                     ProjectTask,
                                     ProjectTaskBase,
                                     ProjectTaskCreate,
                                     ProjectTaskUpdate,
                                     ProjectUpdate,
                                     ProjectWhiteboard,
                                     ProjectWhiteboardUpdate,
                                     ProjectWorkloadSummaryRow,
                                     TaskSupply,
                                     TaskSupplyBase,
                                     TaskSupplyCreate,
                                     TaskSupplyUpdate,
)
