from __future__ import annotations

from backend.schemas._common import CountedStatusResponse, PaginatedResponse, StatusResponse, orm_config

# ── Academy / LMS ────────────────────────────────────────────────────────────
from backend.schemas.academy import (
    AcademyPersonaItem,
    AcademyStudentProfile,
    Assessment,
    AssessmentAttempt,
    AssessmentAttemptSubmit,
    AssessmentOption,
    AssessmentPayload,
    AssessmentQuestion,
    AssessmentQuestionPayload,
    AssessmentUpdate,
    AssignmentSubmission,
    AssignmentSubmissionReview,
    BulkAttendanceCreate,
    BulkAttendanceRecord,
    Certificate,
    Course,
    CourseAttendance,
    CourseAttendanceBase,
    CourseAttendanceCreate,
    CourseListItem,
    CoursePayload,
    CoursePrerequisite,
    CoursePrerequisiteBase,
    CourseStudentItem,
    CourseUpdate,
    DashboardMetrics,
    DashboardMetricsResponse,
    Enrollment,
    EnrollmentCreate,
    EnrollmentResponse,
    FormalActa,
    FormalActaCloseRequest,
    ForumThread,
    ForumThreadBase,
    ForumThreadCreate,
    GradeSubmissionPayload,
    Lesson,
    LessonPayload,
    LessonUpdate,
    MyCertificateItem,
    MyProfileResponse,
    MyProgressItem,
    PilotReadiness,
    PilotReadinessResponse,
    ProgressUpdate,
    Resource,
    ScheduleItem,
    SubmissionListItem,
)

# ── Admin ────────────────────────────────────────────────────────────────────
from backend.schemas.admin import (  # noqa: F401
    AdminCommentRead,
    AdminDonationCategoryCreate,
    AdminDonationCategoryRead,
    AdminDonationCategoryUpdate,
    AdminLocationCreate,
    AdminLocationRead,
    AdminLocationUpdate,
    AdminMilestoneAward,
    AdminMilestoneRead,
    AdminModuleRoleAssign,
    AdminModuleRoleRead,
    AdminPermissionModule,
    AdminPersonaRead,
    AdminProvisionResult,
    AdminRoleCreate,
    AdminRoleRead,
    AdminRoleUpdate,
    AdminSocialCreate,
    AdminSocialRead,
    AdminSocialUpdate,
    AdminStatsRead,
    AdminUserCreate,
    AdminUserPermissionsRead,
    AdminUserRead,
    AdminUserUpdate,
    AdminUserWithRolesRead,
    AdminVariableCreate,
    AdminVariableRead,
    AdminVariableUpdate,
)
from backend.schemas.agenda import AgendaEvent, AgendaEventCreate

# ── Agents ───────────────────────────────────────────────────────────────────
from backend.schemas.agents import AgentInsight, AgentInsightCreate, AgentTask, AgentTaskCreate, AgentTaskUpdate

# ── Auth v3 ──────────────────────────────────────────────────────────────────
from backend.schemas.auth_v3 import (
    AuthStatsSummary,
    CambioPasswordRequest,
    ForgotPasswordRequest,
    LogSeguridadRead,
    MedallaCreate,
    MedallaRead,
    MedallaUsuarioRead,
    MfaRecoveryResponse,
    MfaSetupResponse,
    MfaVerifyRequest,
    NivelGamificadoBase,
    NivelGamificadoCreate,
    NivelGamificadoRead,
    NotificacionRead,
    PreferenciaUIRead,
    PreferenciaUIUpdate,
    RecordatorioCreate,
    RecordatorioRead,
    ResetPasswordRequest,
    RolPlataformaBase,
    RolPlataformaCreate,
    RolPlataformaRead,
    RolPlataformaUpdate,
    TokenResponse,
    TokenSesionRead,
    UsuarioBase,
    UsuarioCreate,
    UsuarioLogin,
    UsuarioRead,
    UsuarioRolModuloBase,
    UsuarioRolModuloCreate,
    UsuarioRolModuloRead,
    UsuarioSelfUpdate,
    UsuarioUpdate,
)
from backend.schemas.auth_v3 import (
    RefreshTokenRequest as AuthRefreshTokenRequest,
)

# ── Chat / Direct Messages ───────────────────────────────────────────
from backend.schemas.chat import (
    ChatMessageAdminRead,
    ConversationCreate,
    ConversationParticipantRead,
    ConversationRead,
    DirectMessageCreate,
    DirectMessageItem,
    ReplyPreview,
)

# ── CMS ──────────────────────────────────────────────────────────────────────
from backend.schemas.cms import (
    CmsAbTestApplyWinner,
    CmsAbTestCreate,
    CmsAbTestEventCreate,
    CmsAbTestEventRead,
    CmsAbTestRead,
    CmsAbTestResults,
    CmsAbTestUpdate,
    CmsCategoryCreate,
    CmsCategoryRead,
    CmsCategoryUpdate,
    CmsFormCreate,
    CmsFormPublicRead,
    CmsFormRead,
    CmsFormSubmissionCreate,
    CmsFormSubmissionCreateV2,
    CmsFormSubmissionPaginated,
    CmsFormSubmissionRead,
    CmsFormUpdate,
    CmsMediaCreate,
    CmsMediaRead,
    CmsMediaUpdate,
    CmsMenuCreate,
    CmsMenuItemCreate,
    CmsMenuItemRead,
    CmsMenuItemReorderItem,
    CmsMenuItemReorderPayload,
    CmsMenuItemUpdate,
    CmsMenuRead,
    CmsMenuUpdate,
    CmsMetrics,
    CmsNewsletterCreate,
    CmsNewsletterRead,
    CmsNewsletterUpdate,
    CmsPageClone,
    CmsPageCreate,
    CmsPageRead,
    CmsPageUpdate,
    CmsPageVersionRead,
    CmsPopupCreate,
    CmsPopupRead,
    CmsPopupUpdate,
    CmsPostCommentCreate,
    CmsPostCommentListResponse,
    CmsPostCommentPublicRead,
    CmsPostCommentRead,
    CmsPostCommentStatusUpdate,
    CmsPostCreate,
    CmsPostRead,
    CmsPostReadWithTaxonomies,
    CmsPostUpdate,
    CmsPublicPageRead,
    CmsPublicPostRead,
    CmsPublicSubscribeRequest,
    CmsPublicUnsubscribeRequest,
    CmsPublishLogRead,
    CmsSectionCreate,
    CmsSectionRead,
    CmsSectionReorderItem,
    CmsSectionReorderPayload,
    CmsSectionTypeCreate,
    CmsSectionTypeRead,
    CmsSectionTypeUpdate,
    CmsSectionUpdate,
    CmsSeoSnapshotRead,
    CmsSiteCreate,
    CmsSiteRead,
    CmsSiteUpdate,
    CmsSubscriberCreate,
    CmsSubscriberImportItem,
    CmsSubscriberImportPayload,
    CmsSubscriberRead,
    CmsSubscriberUpdate,
    CmsTagCreate,
    CmsTagRead,
    CmsTagUpdate,
    CmsThemeCreate,
    CmsThemeRead,
    CmsThemeUpdate,
    CmsWorkflowAction,
    PageSeoAudit,
    PastoralProfileRead,
    PastoralProfileUpdate,
    SchedulePagePublish,
    SeoAuditResponse,
    SeoFinding,
    SeoFindingSeverity,
    SiteSeoStats,
)
from backend.schemas.crm.base import (
    EVENT_TYPES,
    MINISTRY_ROLES,
    CaseCall,
    CaseCallCreate,
    CaseInteractionCreate,
    CaseTaskCreate,
    CaseTaskUpdate,
    CaseUpdate,
    CasoCreate,
    # ── Pre-registro (plan_de_preregistro) ─────────────────────────────────
    CheckinPayload,
    CheckoutPayload,
    ColombianCity,
    ColombianDepartment,
    CounselingTicket,
    CounselingTicketBase,
    CounselingTicketCreate,
    CounselingTicketUpdate,
    CrmEvent,
    CrmEventBase,
    CrmEventCreate,
    CrmEventPreregistrationConfig,
    CrmEventUpdate,
    CrmSettingsUpdate,
    CrmTask,
    CrmTaskBase,
    CrmTaskCreate,
    CrmTaskUpdate,
    Donation,
    DonationBase,
    DonationCreate,
    DonationUpdate,
    EvangelismStrategy,
    EvangelismStrategyBase,
    EvangelismStrategyCreate,
    EvangelismStrategyUpdate,
    EventAttendance,
    EventAttendanceBase,
    EventAttendanceCreate,
    EventAudienceType,
    EventCampaignCreate,
    EventCampaignRead,
    EventCampaignUpdate,
    EventRegistrationBroadcast,
    EventRegistrationBulkImport,
    EventRegistrationCreate,
    EventRegistrationRead,
    EventRegistrationStats,
    EventRegistrationUpdate,
    EventType,
    Family,
    FormationLevel,
    FormationLevelBase,
    FormationLevelCreate,
    FormationLevelUpdate,
    GroupAttendanceReportItem,
    GroupSessionAttendance,
    GroupSessionAttendanceItem,
    GroupSessionReportUpdate,
    GrupoUpdate,
    MessagingSend,
    Persona,
    PersonaCreate,
    PersonaEvangelism,
    PersonaEvangelismBase,
    PersonaEvangelismCreate,
    PersonaEvangelismUpdate,
    PersonaFormation,
    PersonaFormationBase,
    PersonaFormationCreate,
    PersonaFormationUpdate,
    PersonaMentorCandidate,
    PersonaMentorshipCreate,
    PersonaMentorshipResponse,
    PersonaMeshInsight,
    PersonaMeshMetric,
    PersonaMinistryAssignment,
    PersonaMinistryAssignmentBase,
    PersonaMinistryAssignmentCreate,
    PersonaMinistryAssignmentUpdate,
    PersonaPageResponse,
    PersonaPosition,
    PersonaPositionBase,
    PersonaPositionCreate,
    PersonaPositionUpdate,
    PersonaResponse,
    PersonaSelfProfileUpdate,
    PersonaUpdate,
    Position,
    PositionBase,
    PositionCreate,
    PositionUpdate,
    PrayerRequest,
    PrayerRequestBase,
    PrayerRequestCreate,
    PrayerRequestPublicCreate,
    PrayerRequestUpdate,
    PublicEventCancel,
    PublicEventIdentify,
    PublicEventIdentityVerify,
    PublicEventRead,
    PublicEventRegister,
    PublicEventStatusQuery,
    PublicEventVerify,
    RoleCreate,
    RoleUpdate,
    TeachingAssignment,
    TeachingAssignmentBase,
    TeachingAssignmentCreate,
    TeachingAssignmentUpdate,
    VolunteerCreate,
    VolunteerShift,
    VolunteerShiftBase,
    VolunteerShiftCreate,
    VolunteerShiftUpdate,
    VolunteerUpdate,
)

# ── CRM Resources (Biblioteca de Recursos) ───────────────────────────
from backend.schemas.crm.resources import (  # noqa: F401
    BitacoraEnvioOut,
    CategoriaRecursoCreate,
    CategoriaRecursoOut,
    CategoriaRecursoUpdate,
    EnviarPlantillaPayload,
    PlantillaMensajeCreate,
    PlantillaMensajeOut,
    PlantillaMensajeUpdate,
    RecursoAdjuntoOut,
)

# ── Dashboard & Analytics ───────────────────────────────────────────────────
from backend.schemas.dashboard import (
    AcademyDashboard,
    AdminGlobalDashboard,
    ChartDataPoint,
    CrmDashboard,
    FinanceDashboard,
    MetricCard,
    ProjectsDashboard,
)

# ── CRM / Pastoral ───────────────────────────────────────────────────────────
# ── Evangelism (refactor) ────────────────────────────────────────────────────
from backend.schemas.evangelism import (
    AsistenciaBulkCreate,
    AsistenciaBulkItem,
    AsistenciaGrupoCreate,
    AsistenciaSesionBase,
    AsistenciaSesionCreate,
    AsistenciaSesionResponse,
    AsistenciaSesionUpdate,
    ClaseEstrategiaEnum,
    EstadoAsistenciaEnum,
    EstadoSesionEnum,
    EstrategiaEvangelismoBase,
    EstrategiaEvangelismoCreate,
    EstrategiaEvangelismoResponse,
    EstrategiaEvangelismoUpdate,
    FrecuenciaEnum,
    GrupoEvangelismoCreate,
    GrupoEvangelismoResponse,
    GrupoEvangelismoUpdate,
    MotivoExcusaBase,
    MotivoExcusaCreate,
    MotivoExcusaResponse,
    MotivoExcusaUpdate,
    ParticipanteGrupoBase,
    ParticipanteGrupoConRol,
    ParticipanteGrupoCreate,
    ParticipanteGrupoResponse,
    ParticipanteGrupoUpdate,
    RegistroSeguimientoBase,
    RegistroSeguimientoCreate,
    RegistroSeguimientoResponse,
    RegistroSeguimientoUpdate,
    RolEnGrupoEnum,
    RolPersonalizadoEstrategiaBase,
    RolPersonalizadoEstrategiaCreate,
    RolPersonalizadoEstrategiaResponse,
    RolPersonalizadoEstrategiaUpdate,
    SesionGrupoCreate,
    SesionGrupoResponse,
    SesionGrupoUpdate,
    TipoSeguimientoEnum,
)

# ── Governance / Audit ───────────────────────────────────────────────────────
from backend.schemas.governance import AdminAuditLog, AutomationRuleCreate, AutomationRuleRead, AutomationRuleUpdate

# ── Identity & Auth ──────────────────────────────────────────────────────────
from backend.schemas.identity import (
    RefreshTokenRequest,
    Role,
    RoleBase,
    RoleCreate,
    Token,
    TokenUser,
    User,
    UserBase,
    UserCreate,
    UserSelfUpdate,
    UserUpdate,
)

# ── Notifications / Comms ────────────────────────────────────────────────────
from backend.schemas.notifications import CommunicationLog, CommunicationLogCreate, CommunicationLogUpdate, Notification

# ── Operational / Misc ───────────────────────────────────────────────────────
from backend.schemas.operational import (
    CommunityBoardCard,
    CommunityBoardCardCreate,
    CommunityBoardCardUpdate,
    Milestone,
    MilestoneCreate,
    MilestoneUpdate,
    PastorRadarSchema,
    PublicRegistrationCreate,
    SupportTicket,
    SupportTicketCreate,
)

# ── Projects ─────────────────────────────────────────────────────────────────
# ── Projects (canonical) ────────────────────────────────────────────────────
from backend.schemas.projects import (  # noqa: F401
    InboxReadToggle,
    Project,
    ProjectActivityItem,
    ProjectActivityLog,
    ProjectAnalytics,
    ProjectAttachment,
    ProjectBase,
    ProjectCommentBase,
    ProjectCommentCreate,
    ProjectCommentCreateWithProject,
    ProjectCommentItem,
    ProjectCommentUpdate,
    ProjectCreate,
    ProjectDocument,
    ProjectDocumentCreate,
    ProjectDocumentRead,
    ProjectDocumentUpdate,
    ProjectInboxItem,
    ProjectMember,
    ProjectMemberCreate,
    ProjectMessageCreate,
    ProjectMessageItem,
    ProjectMilestone,
    ProjectMilestoneBase,
    ProjectMilestoneUpdate,
    ProjectPhaseInput,
    ProjectPhaseSchema,
    ProjectPortfolioSummaryRow,
    ProjectTask,
    ProjectTaskBase,
    ProjectTaskCreate,
    ProjectTaskUpdate,
    ProjectUpdate,
    ProjectWhiteboard,
    ProjectWhiteboardUpdate,
    ProjectWorkloadSummaryRow,
    TaskSupply,
    TaskSupplyBase,
    TaskSupplyCreate,
    TaskSupplyUpdate,
)
from backend.schemas.wiki import WikiPageCreate, WikiPageRead, WikiPageUpdate, WikiPageVersionRead  # noqa: F401
